export interface RegisterDto{
    email:string;
    password:string;
    rol:number;
    nombre:string;
    apellido:string;
    tipoDocumento:number;
    documento:string;
    genero:number;
    fechaNacimiento:Date;
    telefono:string;
    tipoOcupacion:string;
    codigoOcupacion:number;
    eps:string;
    codigoDepartamento:number;
    codigoMunicipio:number;
    codigoSede:number;
    factorPrestacional?:number;
}