INSERT INTO tipos_documento (codigo,descripcion) VALUES
	 (1,'CÉDULA DE CIUDADANÍA'),
	 (2,'NIT'),
	 (3,'CÉDULA DE EXTRANJERÍA'),
	 (4,'NUIP'),
	 (5,'PASAPORTE'),
	 (6,'TARJETA DE IDENTIDAD'),
	 (7,'PERMISO ESPECIAL DE PERMANENCIA');
