INSERT INTO departamentos  (codigo, descripcion) VALUES
	('1', 'ANTIOQUIA'),
	('2', 'ATLANTICO'),
	('3', 'BOGOTA D.C.'),
	('4', 'BOLIVAR'),
	('5', 'BOYACA'),
	('6', 'CALDAS'),
	('7', 'CAQUETA'),
	('8', 'CAUCA'),
	('9', 'CESAR'),
	('10', 'CORDOBA'),
	('11', 'CUNDINAMARCA'),
	('12', 'CHOCO'),
	('13', 'HUILA'),
	('14', 'LA GUAJIRA'),
	('15', 'MAGDALENA'),
	('16', 'META'),
	('17', 'NARIÑO'),
	('18', 'N. DE SANTANDER'),
	('19', 'QUINDIO'),
	('20', 'RISARALDA'),
	('21', 'SANTANDER'),
	('22', 'SUCRE'),
	('23', 'TOLIMA'),
	('24', 'VALLE DEL CAUCA'),
	('25', 'ARAUCA'),
	('26', 'CASANARE'),
	('27', 'PUTUMAYO'),
	('28', 'SAN ANDRES'),
	('29', 'AMAZONAS'),
	('30', 'GUAINIA'),
	('31', 'GUAVIARE'),
	('32', 'VAUPES'),
	('33', 'VICHADA');