CREATE TABLE `ausentismo` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fecha_inicio` date DEFAULT NULL,
  `fecha_fin` date DEFAULT NULL,
  `hora_inicio` time DEFAULT '00:00:00',
  `hora_fin` time DEFAULT '00:00:00',
  `empleado_documento` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `estado` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `activo` tinyint DEFAULT '0',
  `fecha_creacion` date DEFAULT NULL,
  `fecha_aprobacion` date DEFAULT NULL,
  `observacion` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `cod_contingencia` int NOT NULL,
  `cod_proceso` int DEFAULT NULL,
  `cod_diagnostico` varchar(100) CHARACTER SET latin1 COLLATE latin1_spanish_ci DEFAULT NULL,
  `supervisor_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ausentismo_FK` (`empleado_documento`),
  KEY `ausentismo_FK_1` (`cod_contingencia`),
  KEY `ausentismo_FK_2` (`cod_proceso`),
  KEY `ausentismo_FK_3` (`cod_diagnostico`),
  CONSTRAINT `ausentismo_FK` FOREIGN KEY (`empleado_documento`) REFERENCES `empleados` (`documento`),
  CONSTRAINT `ausentismo_FK_1` FOREIGN KEY (`cod_contingencia`) REFERENCES `contingencias` (`codigo`),
  CONSTRAINT `ausentismo_FK_2` FOREIGN KEY (`cod_proceso`) REFERENCES `procesos` (`codigo`),
  CONSTRAINT `ausentismo_FK_3` FOREIGN KEY (`cod_diagnostico`) REFERENCES `diagnosticos` (`codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;